services:
  app:
    container_name: "app"
    build: .
    environment:
      SETTINGS: deploy/backend
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
      alembic:
        condition: service_started

  database:
    container_name: "database"
    image: postgres:15-alpine3.18
    env_file:
      - ./deploy/postgres.env
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      database:
        condition: service_healthy

volumes:
  db:
    driver: local