[log]
level = 'DEBUG'
[database]
url = "postgresql+asyncpg://postgres:postgres@database:5432/"
[api]
project_name = 'ricardos_cactuses'
prefix = "/api/v1"
host = '0.0.0.0'
port = 8000
backend_cors_origins = ['http://localhost', 'http://localhost:8010']
[casdoor]
administrador_username = 'yanacist'
administrador_password = 'uno_dos_tres_ya_dostal_svoi_svinorez'
validator_key = ''
ednpoint = 'http://localhost:80xx'
client_id = ''
client_secret = ''
certificate = ''
org_name = ''